spring:
  application:
    name: calculate-percentage
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/tenpo_db
    username: tenpo_user
    password: tenpo_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  redis:
    host: redis
    port: 6379
  cache:
    type: redis

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html


server:
  port: 8181